name: DEPLOY TO STAGING

on:
    push:
        branches: [ dev, main ]
    pull_request:
        types : [closed]
        branches:
            - main

jobs:
    aws-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: main
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: 16
            - run: npm install
            - run: npm run build
            - name: Deploy to Server
              uses: easingthemes/ssh-deploy@v2.1.1
              env:
                    SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
                    ARGS: "-rltgoDzvO --delete"
                    SOURCE: "dist/"
                    REMOTE_HOST: "ec2-54-157-248-112.compute-1.amazonaws.com"
                    REMOTE_USER: ubuntu
                    TARGET: "/var/www/html/survey-frontend"

